# Generated by Django 3.0.5 on 2020-05-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_auto_20200504_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebayitem',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
