# Generated by Django 3.0.5 on 2020-05-04 14:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alerts', '0004_auto_20200504_1503'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notification',
            new_name='NotificationRoute',
        ),
        migrations.AlterModelOptions(
            name='notificationroute',
            options={'verbose_name': 'Notification Route', 'verbose_name_plural': 'Notifications Routes'},
        ),
    ]
