# Generated by Django 3.0.5 on 2020-05-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_auto_20200504_1509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationroute',
            options={'verbose_name': 'Notification Route', 'verbose_name_plural': 'Notification Routes'},
        ),
        migrations.AlterField(
            model_name='wanteditem',
            name='condition',
            field=models.IntegerField(choices=[(0, 'N/A'), (1000, 'New'), (1500, 'New Other'), (1750, 'New with defects'), (2000, 'Manufacturer refurbished'), (2500, 'Seller refurbished'), (2750, 'Like New'), (3000, 'Used'), (4000, 'Very Good'), (5000, 'Good'), (6000, 'Acceptable'), (7000, 'For parts or not working')], default=None, null=True),
        ),
    ]
