# Generated by Django 3.0.5 on 2020-05-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0007_notificationroute_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebayitem',
            name='auction_or_fixed',
            field=models.CharField(default='A', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ebayitem',
            name='seller_feedback',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wanteditem',
            name='located_in',
            field=models.CharField(default='GB', max_length=30),
        ),
    ]
