# Generated by Django 3.0.5 on 2020-05-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0008_auto_20200505_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebayitem',
            name='item_id',
            field=models.BigIntegerField(),
        ),
    ]
