# Generated by Django 3.0.5 on 2020-05-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0011_notificationroute_include_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebayitem',
            name='passed_filter',
            field=models.BooleanField(default=True),
        ),
    ]
